name: 'dbt_core'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_core'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# 🏗️ LAYERED ARCHITECTURE (MEDALLION ARCHITECTURE)
# Each layer has its specific dataset in BigQuery
models:
  dbt_core:
    # 🥈 STAGING LAYER (Silver) - Cleaned and standardized data  
    staging:
      +materialized: view
      +schema: staging
      
    # 🥇 MARTS LAYER (Gold) - Analytics-ready data
    marts:
      +materialized: table
      +schema: marts
